version: '3.8'

services:
  scraper:
    build: .
    env_file: .env
    volumes:
      - ./src:/app/src
    depends_on:
      - api

  api:
    build: .
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src